export const lottie = {
  threeDotLoading: require('./threeDotLoading.json'),
  skeletonCardAppointment: require('./skeletonCardAppointment.json'),
  skeletonCardHello: require('./skeletonCardHello.json'),
  skeletonInput: require('./skeletonInput.json'),
  skeletonActiveDoctor: require('./skeletonActiveDoctor.json'),
  skeletonCardPackageClinic: require('./skeletonCardPackageClinic.json'),
  skeletonClinicMain: require('./skeletonClinicMain.json'),
  skeletonComingActivity: require('./skeletonComingActivity.json'),
  skeletonComingTab: require('./skeletonComingTab.json'),
  skeletonDoctor: require('./skeletonDoctor.json'),
  skeletonHealthPackage: require('./skeletonHealthPackage.json'),
  skeletonHistoryTab: require('./skeletonHistoryTab.json'),
  skeletonListLatestChat: require('./skeletonListLatestChat.json'),
  skeletonPoint: require('./skeletonPoint.json'),
  skeletonRecommendPackage: require('./skeletonRecommendPackage.json'),
  skeletonHeaderClinic: require('./skeletonHeaderClinic.json'),
  skeletonMemberCard: require('./skeletonMemberCard.json'),
  skeletonTierMemberScreen: require('./skeletonTierMemberScreen.json'),
  skeletonHistoryPointScreen: require('./skeletonHistoryPointScreen.json'),
  skeletonDetailAccountScreen: require('./skeletonDetailAccountScreen.json'),
}
