export const svgs = {
  SVGCardBeginnerMember: require('./SVGCardBeginnerMember.svg'),
  SVGCardEliteMember: require('./SVGCardEliteMember.svg'),
  SVGCardPlatinumMember: require('./SVGCardPlatinumMember.svg'),
  SVGCardPlusMember: require('./SVGCardPlusMember.svg'),
  SVGChipPlusMember: require('./SVGChipPlusMember.svg'),
  SVGChipBeginnerMember: require('./SVGChipBeginnerMember.svg'),
  SVGChipEliteMember: require('./SVGChipEliteMember.svg'),
  SVGChipPlatinumMember: require('./SVGChipPlatinumMember.svg'),
  SVGLogoHealthCare: require('./SVGLogoHealthCare.svg'),
  SVGHealthCare: require('./SVGHealthCare.svg'),
  SVGSyringe: require('./SVGSyringe.svg'),
  SVGPatient: require('./SVGPatient.svg'),
  SVGHospital: require('./SVGHospital.svg'),
  SVGMessage: require('./SVGMessage.svg'),
  SVGLiver: require('./SVGLiver.svg'),
  SVGPsychiatrist: require('./SVGPsychiatrist.svg'),
  SVGWater: require('./SVGWater.svg'),
  SVGKidney: require('./SVGKidney.svg'),
  SVGCancer: require('./SVGCancer.svg'),
  SVGWorker: require('./SVGWorker.svg'),
  SVGLover: require('./SVGLover.svg'),
  SVGFamily: require('./SVGFamily.svg'),
  SVGCheck: require('./SVGCheck.svg'),
  SVGCardCourse: require('./SVGCardCourse.svg'),
  SVGLogoHealthCareBold: require('./SVGLogoHealthCareBold.svg')
}
